### ISSUE TITLE
How can I change the background color of MetaOutput window ?

### ISSUE THREAD

**Issue by kgh02017** [viacheslav-lozinskyi/MetaOutput#12]
Thanks for this great extension.
I use MetaOutput with VS2022. 
I'd like to change the background color of MetaOutput window (dark red color in the screenshot below) , but I'm not sure what element of color should be changed.
Can I change the color by using Environment - Fonts and Colors configuration in VS2022 Options ?

![metaoutput](https://user-images.githubusercontent.com/32434502/161384760-2b44e011-e6c8-4d27-9d06-54209ae31be0.png)

**Comment by viacheslav-lozinskyi** [comment]
Thank you for appreciation of my work.

Colors are taken from actual Visual Studio theme.
Therefore it is possible to change only together with theme changing.
Any possibility to change separate colors are not available.

**Comment by kgh02017** [comment]
Thanks for your response.
I'll try to change VS theme file.
