### ISSUE TITLE
Add a setting to select the default mode or memorize the last setting

### ISSUE THREAD

**Issue by tomikaa87** [viacheslav-lozinskyi/MetaOutput#14]
Hi, I have an improvement idea.

MetaOutput should provide us a setting to define which mode should be the default and select it automatically when build/debugging/etc. starts and ends.

The current behavior is to reset the mode to "Content highlight mode". For example if I prefer "Filter mode" I must switch to it manually every time. In addition, switching modes clears the filter expression end I have to set it back again manually.

My suggestion is to add sub-menu "Default mode" to "Settings" with the following elements:
* Filter mode
* Content highlight mode
* Comment highlight mode
* Console mode
You could use "checkable" menu items to indicate the current setting.

=== OR ===

A simpler approach could be memorizing the last mode and don't switch over to another automatically.

Also the filter expression (the text in the input box next to the mode switch buttons) should be retained.

**Comment by viacheslav-lozinskyi** [comment]
This feature is already implemented in MetaOutput 1.1.1.195.
It's already released.
Please see if the problem is solved.

Thank you in advance.
