### ISSUE TITLE
text to audio

### ISSUE THREAD

**Issue by stochmal** [viacheslav-lozinskyi/MetaOutput#4]
I like to use text to audio but unfortunately only "Test run finished" is converted. Need to know if passed or failed.
![image](https://user-images.githubusercontent.com/12511085/126966335-6ecde62e-64e9-4128-813c-4be2b9034103.png)

**Comment by viacheslav-lozinskyi** [comment]
You can make visible source "COMMAND", and there will be available message "COMMAND: Build.Failed".
This text can be played and you will know about this fail.
![devenv_8s8Ql9jkiH](https://user-images.githubusercontent.com/51988029/126968429-81714dd0-c674-4982-b6ac-433053dd23dc.png)

**Comment by stochmal** [comment]
Build is OK but TEST is failing and no audio cue
![image](https://user-images.githubusercontent.com/12511085/126969582-5f001f8f-7d6a-45cb-a24a-3ef6d6d70e0e.png)

**Comment by viacheslav-lozinskyi** [comment]
Ok, I will fix it.
Will be implemented in next release.

Thank you for feedback.

**Comment by stochmal** [comment]
Cool let me know when you have something. ;-)

**Comment by viacheslav-lozinskyi** [comment]
ok :)

**Comment by viacheslav-lozinskyi** [comment]
Done in MetaOutput [2.0.3](https://github.com/viacheslav-lozinskyi/MetaOutput/releases/tag/v2.0.3).
Please check it.

**Comment by stochmal** [comment]
works nicely now for pass and fail :smile:
