### ISSUE TITLE
need to be able to copy text message to clipboard

### ISSUE THREAD

**Issue by stochmal** [viacheslav-lozinskyi/MetaOutput#5]
right-click and have Copy option on popup menu?
![image](https://user-images.githubusercontent.com/12511085/126980448-17987ad9-0d4a-4755-b377-a5bf2aa7810e.png)

**Comment by viacheslav-lozinskyi** [comment]
When you press popup menu on whole trace message, is unclear what should be copied: content, comment, content + comment, timestamp, value, or any combination of those elements.
Therefore approach is next: pressing on some element you move it to search string. There possible to copy in clipboard that you need.

**Comment by stochmal** [comment]
It's quicker to right-click on selected text and copy so when I click on line then it's already copied text to search box. 
Right-click and copy would be really nice to have otherwise must look for copy button.

**Comment by viacheslav-lozinskyi** [comment]
It has sense.
I will made it too.

**Comment by stochmal** [comment]
**========== Test run<<< finished: 27 Tests (26 Passed, 1 >>>Failed<<<, 0 Skipped) run in 3,8 sec ========== @@@SOURCE TEST @@@TYPE ERROR @@@FOREGROUND GREEN**

not sure if @@@ should be there or replaced with actual value?

**Comment by stochmal** [comment]
**========== Test run finished: 27 Tests (26 Passed, 1 Failed, 0 Skipped) run in 3,8 sec ==========**

above using copy button

**Comment by viacheslav-lozinskyi** [comment]
It is code on TML.

**Comment by viacheslav-lozinskyi** [comment]
You can save it to file and import it by "Popup Menu/Tools/Import...".
Result will be the same as you see before copying ;)

**Comment by stochmal** [comment]
after import from file looks like <<< is being added
![image](https://user-images.githubusercontent.com/12511085/127359393-aeb28257-51f9-489c-9cb7-9a3ff5c6c117.png)

**Comment by viacheslav-lozinskyi** [comment]
It's bug, I will fix it.

**Comment by viacheslav-lozinskyi** [comment]
This issue I will close.
Found bug will be fixed in next release.
Thank you for help ;)
