### ISSUE TITLE
Icons should be at the top like screenshot below

### ISSUE THREAD

**Issue by stochmal** [viacheslav-lozinskyi/MetaOutput#6]
![image](https://user-images.githubusercontent.com/12511085/127128503-015293ce-34b4-48b2-b9e6-5140caa5544a.png)

**Comment by viacheslav-lozinskyi** [comment]
Sorry, but I don't understand your request

**Comment by stochmal** [comment]
Every window in VS at the bottom pane has icons at the top except MetaOutput.
Not sure why you placed icons at the bottom?
![image](https://user-images.githubusercontent.com/12511085/127142277-3990a599-bdb1-4240-ac7a-31f850974050.png)

**Comment by viacheslav-lozinskyi** [comment]
I understand.

The reason - is the vertical tool size.
When you add toolbar, you take part of useful space.

For example, try to add toolbar to your screenshot. It will take 15-20% of useful space.
It's too much, and it is a reason why I didn't use standard approach.
It is a reason, why I will never use toolbar in this tool.

I know that is differ from guideline for Visual Studio tools, but MetaOutput is complete violation of usual approach.
If I will follow guidelines will be [VsColorOutput](https://marketplace.visualstudio.com/items?itemName=MikeWard-AnnArbor.VSColorOutput). Not MetaOutput...

**Comment by stochmal** [comment]
another problem is that when clicking on icon then you can accidentally click on another tab
![image](https://user-images.githubusercontent.com/12511085/127145793-5186d764-3170-41e9-885a-1dc3012eb516.png)

**Comment by viacheslav-lozinskyi** [comment]
I see more disadvantages in standard approach than in that I use.
Therefore it will not be changed.

**Comment by stochmal** [comment]
Should be setting so user can have choice to place icons at top or bottom.
Another problem is that icons are too small making it hard to click on them.

**Comment by viacheslav-lozinskyi** [comment]
All icons are placed at horizontal scroller location.
In earlier versions there was scroller too.

Button size is equal horizontal scroller height (it less the tollbar height, and therefore it better).
Also this panel has variable part - list of used sources.
It can take much width:
![image](https://user-images.githubusercontent.com/51988029/127288296-9e5dfad3-4147-41c6-a5b7-211ab68e7dfe.png)

If to make icon height bigger - will be new problem. Some sources will disappear.
Also source icon on this panel and in trace messages will have different size, and searching necessary source on this panel will require more efforts from user.
In fact it is multi parametric problem, and standard approach is not the best.

P.S.
I much time thought about this issue earlier.
I did many changes of this functionality in previous versions, and current implementation is the best.
